### PR TITLE
Basic support for django rest framework

### PR DESCRIPTION
**Pull request by jeffgabhart**
Check cls for django rest framework viewsets. This was enough for me to pull basic docstring information from the class.

### CODE REVIEW

**Comment by kluchrj** [comment]
Thanks. I squashed the commit.

**Comment by jeffgabhart** [comment]
@kluchrj I think this breaks non-CBV's and should be reverted.

**Comment by kluchrj** [comment]
Non-CBVs seem to be working fine for me, and the tests are passing. Is there an issue you are encountering with the newer version?

From what I understand, the change shouldn't have any effect if the view doesn't define `cls`. Django's CBVs don't define that as far as I can tell.

**Comment by jeffgabhart** [comment]
ok, thanks, maybe it's something I messed up as I try to get DRF `@action` identified for custom permission classes. Sorry to bother.

**Pull request merged**
